[package]
name = "chapter9-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Unwinding the Stack or Aborting in Response to a Panic
[profile.release]
panic = 'abort'